apiVersion: v1
kind: Service
metadata:
  name: fluentd
  namespace: logger
  labels:
    app: fluentd
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
spec:
  externalTrafficPolicy: Local
  ports:
  - name: tcp
    port: 24224
    protocol: TCP
    targetPort: 24224
  # - name: udp
  #   port: 5140
  #   protocol: UDP
  #   targetPort: 5140
  selector:
    app: fluentd
  type: LoadBalancer
