apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluentd-deployment
  namespace: logger
  labels:
    app: fluentd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      containers:
        - name: fluentd
          image: fluent/fluentd:v1.2.2
          ports:
            - name: tcp
              containerPort: 24224
              protocol: TCP
            - name: udp
              containerPort: 5140
              protocol: UDP
          lifecycle:
            preStop:
              exec:
                command: ["echo", "stopping"]
